etc/xdg/autostart/lockfs-notify.desktop				etc/xdg/autostart
lib/bilibop/lockfs_mount_helper					lib/bilibop
lib/bilibop/lockfs.sh						lib/bilibop
usr/bin/lockfs-notify						usr/bin
usr/share/initramfs-tools/hooks/bilibop-lockfs			usr/share/initramfs-tools/hooks
usr/share/initramfs-tools/scripts/init-top/bilibop-lockfs	usr/share/initramfs-tools/scripts/init-top
usr/share/initramfs-tools/scripts/local-bottom/bilibop-lockfs	usr/share/initramfs-tools/scripts/local-bottom
