#! /bin/sh
#
# INIT script to check whether we're on batteries, and so start with laptop 
# mode etc enabled.
#
DEPENDS='Linux/proc'
FUNCS=/usr/share/acpi-support/power-funcs

test -f "$FUNCS" && . "$FUNCS"

case "$1" in

    start)
	start $DEPENDS || exit 1

	if [ -f "$FUNCS" -a -d /proc/acpi -a -d /proc/acpi/ac_adapter ]; then 
		grep -q off-line /proc/acpi/ac_adapter/*/state >/dev/null 2>&1
		if [ $? = 0 ]; then
			$LAPTOP_MODE start
			$HDPARM -S 12 /dev/hda
			$HDPARM -B 1 /dev/hda
		fi
	fi

	exit 0
	;;

    stop)
	if [ -f "$FUNCS" -a -d /proc/acpi/ac_adapter ]; then
		grep -q off-line /proc/acpi/ac_adapter/*/state >/dev/null 2>&1
		if [ $? = 0 ]; then
			$HDPARM -B 255 /dev/hda
			$LAPTOP_MODE stop
		fi
	fi

	stop $DEPENDS
	;;
esac
