#! /bin/sh
#
# The virtual filesystems /proc and /sys .
#
case "$1" in

    start)
    	mount -n -t proc proc /proc
	mount -n -t sysfs sysfs /sys
	exit 0
	;;

    stop)
	umount -n /sys
    	umount -n /proc
	;;
esac
