#! /bin/sh
#
# Advanced Configuration and Power Interface daemon
#
DEPENDS='root'

case "$1" in

    start)
	mystart $DEPENDS || exit 1

	OPTIONS=""
	[ -f /etc/default/acpid ] && . /etc/default/acpid

	LOC="/lib/modules/`uname -r`/kernel/drivers/acpi"

	if [ "$MODULES" = "all" ]; then
		MODULES=""
		for F in "$LOC"/*.o; do MODULES="$MODULES `basename $F .o`"; done
		for F in "$LOC"/*.ko; do MODULES="$MODULES `basename $F .ko`"; done
	fi

	if [ -n "$MODULES" ]; then
	        for mod in $MODULES; do
			modprobe $mod
	        done
	fi

	/usr/sbin/acpid -c /etc/acpi/events $OPTIONS || {
		mystop $DEPENDS;
		exit 1;
	}

	exit 0
	;;

    stop)
	killall /usr/sbin/acpid

	mystop $DEPENDS
	;;
esac
