#! /bin/sh
#
# The File Alteration Monitor (FAM) daemon.
#
DEPENDS='portmap'
PROG=/usr/sbin/famd
ARGS="-f -L -T 0"

case "$1" in

    start)
	test -x $PROG || exit 5

	mystart $DEPENDS || exit 1

	mystart $PROG $ARGS || {
		mystop $DEPENDS;
		exit 1;
	}

	exit 0
	;;

    stop)
	mystop $PROG

	mystop $DEPENDS
	;;
esac
