#! /bin/sh
DEPENDS='root'
syslogd='/sbin/syslogd -n'
klogd='/sbin/klogd -n'

case "$1" in

    start)
	mystart $DEPENDS || exit 1

	mystart $syslogd
	mystart $klogd

	if [ ! -e /dev/xconsole ]; then
		mknod -m 640 /dev/xconsole p
	else
		chmod 0640 /dev/xconsole
	fi
	chown root:adm /dev/xconsole

	exit 0
	;;

    stop)
	mystop $klogd
	mystop $syslogd

	mystop $DEPENDS
	;;

    restart)
	echo "Restarting logging daemons..."
	mystop $klogd
	mystop $syslogd
	sleep 1
	mystart $syslogd
	mystart $klogd
	;;
esac
