#! /bin/sh
#
# Terminal services for users.
#
DEPENDS='console fs'

case "$1" in

    start)
	mystart $DEPENDS || exit 1

	echo "Starting terminal services..."
	mystart /sbin/getty /dev/tty2 9600
	mystart /sbin/getty /dev/tty3 9600

	# Don't forget to stop what you start!

	# Hardwired serial terminal
	#start /sbin/getty YOURDEVICENAME 9600,2400,1200

	# Dial-in terminal (modem)
	#start /sbin/getty -h -I "ATZ" -m -t 30 YOURDEVICENAME 9600,2400,1200

	exit 0
	;;

    stop)
	echo "Stopping terminal services..."
	mystop /sbin/getty /dev/tty2
	mystop /sbin/getty /dev/tty3

	#stop /sbin/getty YOURDEVICENAME

	chvt 1
	deallocvt

	mystop $DEPENDS
	;;
esac


#
# Linux device names
# ==================
#
# /dev/tty#	Virtual consoles
#
# /dev/ttyS#	UART serial ports
# /dev/ttyACM#	ACM-compliant USB modems and netmods
# /dev/ttyUSB#	USB serial converters
# /dev/ttyUB#	USB BlueTooth devices
#
# /dev/ttyI#	isdn4linux virtual modem
# /dev/ttyU#	User space serial ports
#
# /dev/ttyH#	Chase serial card
# /dev/ttyC#	Cyclades serial card
# /dev/ttyD#	Digiboard serial card
# /dev/ttyX#	Specialix serial card
# /dev/ttyR#	Comtrol Rocketport serial card
# /dev/ttyL#	SDL RISCom serial card
# /dev/ttyP#	Hayes ESP serial card
# /dev/ttyM0#	PAM Software's multimodem boards
# /dev/ttyV#	Comtrol VS-1000 serial controller
# /dev/ttyM#	ISI serial card
# /dev/ttyT#	Technology Concepts serial card
# /dev/ttySR#	Specialix RIO serial card
# /dev/ttyCH#	Chase Research AT/PCI-Fast serial card
# /dev/ttySI#	SmartIO serial card
# /dev/ttyY#	A2232 serial card
#
# Stallion serial card
#     /dev/ttyE0	Stallion port 0 card 0
#     /dev/ttyE64	Stallion port 0 card 1
#     /dev/ttyE128	Stallion port 0 card 2
#     /dev/ttyE192	Stallion port 0 card 3
#
# Computone IntelliPort II serial card
#     /dev/ttyF0	IntelliPort II board 0, port 0
#     /dev/ttyF64	IntelliPort II board 1, port 0
#     /dev/ttyF128	IntelliPort II board 2, port 0
#     /dev/ttyF192	IntelliPort II board 3, port 0
#
# Specialix IO8+ serial card
#     /dev/ttyW0	First IO8+ port, first card
#     /dev/ttyW1	Second IO8+ port, first card
#     ...
#     /dev/ttyW8	First IO8+ port, second card
#     ...
#
# Moxa Intellio serial card
#     /dev/ttyMX0	First Moxa port
#     /dev/ttyMX1	Second Moxa port
#     ...
#     /dev/ttyMX127	128th Moxa port
#     /dev/moxactl	Moxa control port
#
# Low-density serial ports
#     /dev/ttyLU0	LinkUp Systems L72xx UART - port 0
#     /dev/ttyLU1	LinkUp Systems L72xx UART - port 1
#     /dev/ttyLU2	LinkUp Systems L72xx UART - port 2
#     /dev/ttyLU3	LinkUp Systems L72xx UART - port 3
#     /dev/ttyFB0	Intel Footbridge (ARM)
#     /dev/ttySA0	StrongARM builtin serial port 0
#     /dev/ttySA1	StrongARM builtin serial port 1
#     /dev/ttySA2	StrongARM builtin serial port 2
#     /dev/ttySC0	SCI serial port (SuperH) - port 0
#     /dev/ttySC1	SCI serial port (SuperH) - port 1
#     /dev/ttySC2	SCI serial port (SuperH) - port 2
#     /dev/ttySC3	SCI serial port (SuperH) - port 3
#     /dev/ttyFW0	Firmware console - port 0
#     /dev/ttyFW1	Firmware console - port 1
#     /dev/ttyFW2	Firmware console - port 2
#     /dev/ttyFW3	Firmware console - port 3
#     /dev/ttyAM0	ARM "AMBA" serial port 0
#     ...
#     /dev/ttyAM15	ARM "AMBA" serial port 15
#     /dev/ttyDB0	DataBooster serial port 0
#     ...
#     /dev/ttyDB7	DataBooster serial port 7
#
