#! /bin/sh
#
# The `atd' daemon.
#
DEPENDS='root'
PROG=/usr/sbin/atd
ARGS=""

case "$1" in

    start)
	test -x $PROG || exit 5

	start $DEPENDS || exit 1

	"$PROG" $ARGS

	exit 0
	;;

    stop)
	killall "$PROG"

	stop $DEPENDS
	;;
esac
