#!/bin/sh
#
# Start/stop the cron daemon.
#
DEPENDS='root'
PROG=/usr/sbin/cron
ARGS=''
#ARGS='-l'

case "$1" in

    start)
	test -f "$PROG" || exit 5

	start $DEPENDS || exit 1

	start "$PROG" -f $ARGS

	exit 0
	;;

    stop)
	stop "$PROG"

	stop $DEPENDS
	;;
esac
