#! /bin/sh
#
# The File Alteration Monitor (FAM) daemon.
#
DEPENDS='portmap'
PROG=/usr/sbin/famd
ARGS="-f -L -T 0"

case "$1" in

    start)
	test -x $PROG || exit 5

	start $DEPENDS || exit 1

	start $PROG $ARGS || {
		stop $DEPENDS;
		exit 1;
	}

	exit 0
	;;

    stop)
	stop $PROG

	stop $DEPENDS
	;;
esac
