#! /bin/sh
#
# Kernel and hardware initialization.
#
KERNEL="`uname -s`"

cd etc/init
DEPENDS=`echo "$KERNEL"/*`
cd ../..

case "$1" in

    start)
	start $DEPENDS
	;;

    stop)
	stop $DEPENDS
	;;
esac
