#! /bin/sh
#
# Set hostname and configure network interfaces.
#
DEPENDS='root kernel'

case "$1" in

    start)
	[ -x /sbin/ifup ] || exit 5

	start $DEPENDS || exit 1

	echo "Enabling networking..."
	if [ -e /proc/sys/net/ipv4/conf/all/rp_filter ]; then
		for f in /proc/sys/net/ipv4/conf/*/rp_filter; do
			echo 1 > $f
		done
	fi

	#if [ -e /proc/sys/net/ipv4/tcp_syncookies ]; then
	#	echo 1 > /proc/sys/net/ipv4/tcp_syncookies
	#fi

	#if [ -e /proc/sys/net/ipv4/ip_forward ]; then
	#	echo 1 > /proc/sys/net/ipv4/ip_forward
	#fi

	ifup -a

	exit 0
	;;

    stop)
	echo "Disabling networking..."
	ifdown -a

	stop $DEPENDS
	;;
esac
