#! /bin/sh
#
# Activate swap, then check and remount root filesystem read/write.
#
case "$1" in

    start)
	swapon -a

	fsck=/sbin/fsck
	if [ -f /no_fsck ]; then
		echo "Filesystems are NOT being checked! (/no_fsck exists)" 1>&2
	elif [ ! -x "$fsck" ]; then
		echo "Filesystems are NOT being checked! (fsck is not available)" 1>&2
	else
		"$fsck" -a -C -T /
		RESULT="$?"
		if [ "$RESULT" -gt 2 ]; then
			echo "(fsck returned $RESULT)"
			echo
			echo "The automatic filesystem check has failed.  I need your guidance in order to"
			echo "repair the root filesystem."
			echo
			echo "You must login as \`root' and use the following command:"
			echo
			echo "    fsck /"
			echo
			exit 1
		fi
	fi

	echo "Remounting root filesystem read/write..."
	mount -n -o remount,rw /
	RESULT="$?"
	if [ "$RESULT" -ne 0 ]; then
		echo "The \`mount' command failed with exit code $RESULT .  I dare not proceed!"
		exit 1
	fi
	rm -f /etc/mtab
	mount -f -o remount,rw /

	exit 0
	;;

    stop)

	echo "Remounting root filesystem read-only..."
	initset -x
	mount -f -o remount,ro /
	sync
	sleep 1  # this shouldn't be necessary
	mount -n -o remount,ro / || { lsof | egrep 'w[[:space:]]+[A-Za-z]'; ps axf; sleep 1; mount -n -o remount,ro /; } || { sleep 1; mount -n -o remount,ro /; }
	sync

	swapoff -a
	;;
esac
