#!/bin/sh
#
# The X Display Manager.
#
DEPENDS='fs'
NAME="X display manager"
PROG=/usr/bin/X11/xdm
ARGS='-nodaemon'

case "$1" in

    start)
	test -x "$PROG" || exit 5

	start $DEPENDS || exit 1

	modprobe mousedev >/dev/null 2>&1

	echo "Starting $NAME..."
	start "$PROG" $ARGS

	exit 0
	;;

    stop)
	echo "Stopping $NAME..."
	stop "$PROG"

	stop $DEPENDS
	;;
esac
