.TH halt 8 "December 2007" "halt(8)" "MYINIT 0.4"
.SH NAME
halt \- halt the system
.SH SYNOPSIS
.B halt

.SH DESCRIPTION
The \fBhalt\fP command will cause all services to be stopped, and the system to
halt.
.SH ENVIRONMENT
\fBhalt\fP uses these environment variables:
.IP \fBMYINIT_HOME\fP
This is used to infer the name of the FIFO to use to communicate with
\fIinit\fR.  If this is not set, the default is assumed (\fI/etc/init\fR).
.SH AUTHOR
stamit@stamit.gr
.SH "SEE ALSO"
init(8),
start(8),
stop(8),
initset(8),
reboot(8),
poweroff(8)
