.TH poweroff 8 "December 2007" "poweroff(8)" "MYINIT 0.4"
.SH NAME
poweroff \- power off the system
.SH SYNOPSIS
.B poweroff

.SH DESCRIPTION
The \fBpoweroff\fP command will cause all services to be stopped, and the system
to power off.
.SH ENVIRONMENT
\fBpoweroff\fP uses these environment variables:
.IP \fBMYINIT_HOME\fP
This is used to infer the name of the FIFO to use to communicate with
\fIinit\fR.  If this is not set, the default is assumed (\fI/etc/init\fR).
.SH AUTHOR
stamit@stamit.gr
.SH "SEE ALSO"
init(8),
start(8),
stop(8),
initset(8),
halt(8),
reboot(8)
