.TH start 8 "December 2007" "start(8)" "MYINIT 0.4"
.SH NAME
start \- reference services
.SH SYNOPSIS
.B start
\fIservice1\fR [ \fIservice2\fR ... ]
.br
.B start
\fI/absolute/path/to/program\fR [ \fIargument1\fR [ \fIargument2\fR ... ] ]

.SH DESCRIPTION
The \fBstart\fP command will `reference' a set of services, meaning it will note
that the services are needed and will attempt to start them if they are not
already started.  If a service fails to start, then \fBstart\fP will remove all
references it has added and then it will fail immediately (without waiting for
the services to stop).
.PP
You should use this command to start services and never call the initscripts
directly.
.PP
If \fBstart\fP is given an absolute pathname as the first argument, it will
assume that it is a daemon which must be spawned by \fIinit\fR and then
respawned whenever it exits.  Any remaining arguments will be given to the
daemon whenever it is spawned.
.SH ENVIRONMENT
\fBstart\fP uses these environment variables:
.IP \fBMYINIT\fP
This is set (or not set) by \fIinit\fR.  It must be left unchanged.
.IP \fBMYINIT_HOME\fP
This is used to infer the name of the FIFO to use to communicate with
\fIinit\fR.  If this is not set, the default is assumed (\fI/etc/init\fR).
.SH "EXIT CODE"
If and when all services have been started successfuly, \fBstart\fP will return
0.  Otherwise, it will return nonzero.
.SH AUTHOR
stamit@stamit.gr
.SH "SEE ALSO"
init(8),
stop(8),
initset(8),
reboot(8),
halt(8),
poweroff(8)
